/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";
import * as core from "../../../core";

export const Address: core.schemas.ObjectSchema<Address.Raw, FinixApi.identities.Address> = core.schemas.object({
  streetNumber: core.schemas.property("street_number", core.schemas.string()),
  streetName: core.schemas.property("street_name", core.schemas.string()),
  city: core.schemas.string(),
  state: core.schemas.string(),
});

export declare namespace Address {
  interface Raw {
    street_number: string;
    street_name: string;
    city: string;
    state: string;
  }
}
