/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";
import * as core from "../../../core";

export const BuyerResponse: core.schemas.ObjectSchema<BuyerResponse.Raw, FinixApi.identities.BuyerResponse> =
  core.schemas.object({
    id: core.schemas.string(),
    createdAt: core.schemas.property("created_at", core.schemas.date()),
    application: core.schemas.string(),
  });

export declare namespace BuyerResponse {
  interface Raw {
    id: string;
    created_at: string;
    application: string;
  }
}
