/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const CreateIdentityRequest: core.schemas.Schema<
  CreateIdentityRequest.Raw,
  FinixApi.identities.CreateIdentityRequest
> = core.schemas
  .union("type", {
    merchant: core.schemas.lazyObject(() => serializers.identities.MerchantRequest),
    buyer: core.schemas.lazyObject(() => serializers.identities.BuyerRequest),
  })
  .transform<FinixApi.identities.CreateIdentityRequest>({
    parse: (value) => {
      switch (value.type) {
        case "merchant": {
          return FinixApi.identities.CreateIdentityRequest.merchant(value);
        }
        case "buyer": {
          return FinixApi.identities.CreateIdentityRequest.buyer(value);
        }
        default: {
          return {
            ...(value as any),
            _visit: (visitor) => visitor._other(value),
          };
        }
      }
    },
    json: (value) => value as any,
  });

export declare namespace CreateIdentityRequest {
  type Raw = CreateIdentityRequest.Merchant | CreateIdentityRequest.Buyer;

  interface Merchant extends serializers.identities.MerchantRequest.Raw {
    type: "merchant";
  }

  interface Buyer extends serializers.identities.BuyerRequest.Raw {
    type: "buyer";
  }
}
