/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const Entity: core.schemas.ObjectSchema<Entity.Raw, FinixApi.identities.Entity> = core.schemas.object({
  email: core.schemas.string().optional(),
  firstName: core.schemas.property("first_name", core.schemas.string().optional()),
  lastName: core.schemas.property("last_name", core.schemas.string().optional()),
  personalAddress: core.schemas.property(
    "personal_address",
    core.schemas.lazyObject(() => serializers.identities.Address).optional()
  ),
  phone: core.schemas.string().optional(),
});

export declare namespace Entity {
  interface Raw {
    email?: string | null;
    first_name?: string | null;
    last_name?: string | null;
    personal_address?: serializers.identities.Address.Raw | null;
    phone?: string | null;
  }
}
