/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const MerchantRequest: core.schemas.ObjectSchema<MerchantRequest.Raw, FinixApi.identities.MerchantRequest> =
  core.schemas.object({
    additionalUnderwritingData: core.schemas.property(
      "additional_underwriting_data",
      core.schemas.lazyObject(() => serializers.identities.AdditionalUnderwritingData)
    ),
  });

export declare namespace MerchantRequest {
  interface Raw {
    additional_underwriting_data: serializers.identities.AdditionalUnderwritingData.Raw;
  }
}
