/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";
import * as core from "../../../core";

export const Tags: core.schemas.ObjectSchema<Tags.Raw, FinixApi.identities.Tags> = core.schemas.object({
  propertyName: core.schemas.property("property_name", core.schemas.string().optional()),
});

export declare namespace Tags {
  interface Raw {
    property_name?: string | null;
  }
}
