/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { FinixApi } from "../../..";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.identities.Identity.Raw[], FinixApi.identities.Identity[]> =
  core.schemas.list(core.schemas.lazy(() => serializers.identities.Identity));
