/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface AdditionalUnderwritingData {
  /** The approximate annual ACH sales expected to be processed (in cents) by this merchant (max 10 characters). */
  annualAchVolume?: number;
  /** The approximate average ACH sale amount (in cents) for this merchant. */
  averageAchTransferAmount?: number;
  /** The average credit card sale amount (in cents) for this merchant. */
  averageCardTransferAmount?: number;
  /** Description of this merchant's business (max 200 characters). */
  businessDescription: string;
}
