/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface AssociatedResponse {
  /** The ID of the Identity resource. */
  id: string;
  /** Timestamp of when the object was created. */
  createdAt: Date;
  /** ID of the Application associated with the Identity. */
  application: string;
}
