/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";

export interface BuyerRequest {
  /** The underwriting details required to verify Identities. */
  entity: FinixApi.identities.Entity;
  /** Key value pair for annotating custom meta data (e.g. order numbers). */
  tags: FinixApi.identities.Tags;
}
