/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";

export type CreateIdentityResponse =
  | CreateIdentityResponse.Merchant
  | CreateIdentityResponse.Buyer
  | CreateIdentityResponse.Associated
  | CreateIdentityResponse._Unknown;

export declare namespace CreateIdentityResponse {
  interface Merchant extends FinixApi.identities.MerchantResponse, _Utils {
    type: "merchant";
  }

  interface Buyer extends FinixApi.identities.BuyerResponse, _Utils {
    type: "buyer";
  }

  interface Associated extends FinixApi.identities.AssociatedResponse, _Utils {
    type: "associated";
  }

  interface _Unknown extends _Utils {
    type: void;
  }

  interface _Utils {
    _visit: <Result>(visitor: CreateIdentityResponse._Visitor<Result>) => Result;
  }

  interface _Visitor<Result> {
    merchant: (value: FinixApi.identities.MerchantResponse) => Result;
    buyer: (value: FinixApi.identities.BuyerResponse) => Result;
    associated: (value: FinixApi.identities.AssociatedResponse) => Result;
    _other: (value: { type: string }) => Result;
  }
}

export const CreateIdentityResponse = {
  merchant: (value: FinixApi.identities.MerchantResponse): CreateIdentityResponse.Merchant => {
    const valueWithoutVisit: Omit<CreateIdentityResponse.Merchant, "_visit"> = {
      ...value,
      type: "merchant",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as CreateIdentityResponse.Merchant;
    castedValue._visit = (visitor) => visitor.merchant(value);
    return castedValue;
  },

  buyer: (value: FinixApi.identities.BuyerResponse): CreateIdentityResponse.Buyer => {
    const valueWithoutVisit: Omit<CreateIdentityResponse.Buyer, "_visit"> = {
      ...value,
      type: "buyer",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as CreateIdentityResponse.Buyer;
    castedValue._visit = (visitor) => visitor.buyer(value);
    return castedValue;
  },

  associated: (value: FinixApi.identities.AssociatedResponse): CreateIdentityResponse.Associated => {
    const valueWithoutVisit: Omit<CreateIdentityResponse.Associated, "_visit"> = {
      ...value,
      type: "associated",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as CreateIdentityResponse.Associated;
    castedValue._visit = (visitor) => visitor.associated(value);
    return castedValue;
  },
} as const;
