/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";

export interface Entity {
  email?: string;
  firstName?: string;
  lastName?: string;
  /** The billing address of the buyer. This field is used for identity verification purposes. */
  personalAddress?: FinixApi.identities.Address;
  /** Phone number where the buyer can be reached. */
  phone?: string;
}
