/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";

export type Identity = Identity.Merchant | Identity.Buyer | Identity.Associated | Identity._Unknown;

export declare namespace Identity {
  interface Merchant extends FinixApi.identities.MerchantResponse, _Utils {
    type: "merchant";
  }

  interface Buyer extends FinixApi.identities.BuyerResponse, _Utils {
    type: "buyer";
  }

  interface Associated extends FinixApi.identities.AssociatedResponse, _Utils {
    type: "associated";
  }

  interface _Unknown extends _Utils {
    type: void;
  }

  interface _Utils {
    _visit: <Result>(visitor: Identity._Visitor<Result>) => Result;
  }

  interface _Visitor<Result> {
    merchant: (value: FinixApi.identities.MerchantResponse) => Result;
    buyer: (value: FinixApi.identities.BuyerResponse) => Result;
    associated: (value: FinixApi.identities.AssociatedResponse) => Result;
    _other: (value: { type: string }) => Result;
  }
}

export const Identity = {
  merchant: (value: FinixApi.identities.MerchantResponse): Identity.Merchant => {
    const valueWithoutVisit: Omit<Identity.Merchant, "_visit"> = {
      ...value,
      type: "merchant",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as Identity.Merchant;
    castedValue._visit = (visitor) => visitor.merchant(value);
    return castedValue;
  },

  buyer: (value: FinixApi.identities.BuyerResponse): Identity.Buyer => {
    const valueWithoutVisit: Omit<Identity.Buyer, "_visit"> = {
      ...value,
      type: "buyer",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as Identity.Buyer;
    castedValue._visit = (visitor) => visitor.buyer(value);
    return castedValue;
  },

  associated: (value: FinixApi.identities.AssociatedResponse): Identity.Associated => {
    const valueWithoutVisit: Omit<Identity.Associated, "_visit"> = {
      ...value,
      type: "associated",
    };
    Object.defineProperty(valueWithoutVisit, "_visit", {
      enumerable: false,
      writable: true,
    });
    const castedValue = valueWithoutVisit as Identity.Associated;
    castedValue._visit = (visitor) => visitor.associated(value);
    return castedValue;
  },
} as const;
