/**
 * This file auto-generated by Fern from our API Definition.
 */

import { FinixApi } from "../../..";

export interface MerchantRequest {
  additionalUnderwritingData: FinixApi.identities.AdditionalUnderwritingData;
}
