/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as IdentitiesClient } from "./resources/identities/client/Client";

export declare namespace FinixApiClient {
  interface Options {
    environment?: environments.Environment | string;
    auth?: {
      credentials?: core.Supplier<core.BasicAuth>;
    };
  }
}

export class FinixApiClient {
  constructor(private readonly options: FinixApiClient.Options) {}

  #identities: IdentitiesClient | undefined;

  public get identities(): IdentitiesClient {
    return (this.#identities ??= new IdentitiesClient(this.options));
  }
}
