/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  /**
   * where payments are processed
   */
  Production: "https://finix.payments-api.com/",
  /**
   * for testing
   */
  Sandbox: "https://finix.sandbox-payments-api.com",
} as const;

export type Environment = typeof Environment.Production | typeof Environment.Sandbox;
